### ISSUE TITLE
Add the option to exclude certain topics

### ISSUE THREAD

**Issue by niklas-heer** [Linux-statt-Windows/nodebb-plugin-topic-events#2]
It would be nice to have the option to exclude some topics from displaying any events. Or maybe only display the events for when a topic was moved. 
This cloud be handy for topics such as FAQs.

Maybe something like that: (mockup with "fa-exclamation-circle")
![schnappschuss_051415_053215_pm](https://cloud.githubusercontent.com/assets/1914063/7635086/2d08f94a-fa5f-11e4-99d4-de487d7c6709.jpg)

Clarification:
- The events should still be stored
- The events should just be hidden from the user
- It should be like a toggle, easy to enable and disable

**Comment by niklas-heer** [comment]
The icon should change whether it is enabled or disabled.
- off = "fa fa-toggle-off"
- on = "fa fa-toggle-on" should be colored in "#4bd865"

**Comment by rbeer** [comment]
![topictools](https://cloud.githubusercontent.com/assets/3411649/7720173/7ccc3702-feca-11e4-83ce-efdc05d4b1ba.png)

**PLEASE CARE**
I had to _--ammend / push --force_ the last 3 commits - forgot to tag the issue in commit message. :disappointed:
